import { LocationSite, ReviewItem, SimilarSite, TemporalStep } from './types';

export const INITIAL_SITES: LocationSite[] = [
  {
    id: 'site-01',
    code: 'SITE-01',
    name: 'Kurnool',
    state: 'Andhra Pradesh',
    changeType: 'Road Development',
    confidence: 92,
    priority: 'HIGH',
    date: 'Aug 2026',
    lat: 15.8281,
    lng: 78.0373,
    xPercent: 38,
    yPercent: 44,
    changedArea: '1.84 ha',
    firstObservation: 'June 2026',
    sensor: 'Sentinel-2',
    processingStatus: 'COMPLETED',
    verificationStatus: 'PENDING',
  },
  {
    id: 'site-02',
    code: 'SITE-02',
    name: 'Vijayawada',
    state: 'Andhra Pradesh',
    changeType: 'Construction Expansion',
    confidence: 87,
    priority: 'MEDIUM',
    date: 'Aug 2026',
    lat: 16.5062,
    lng: 80.6480,
    xPercent: 64,
    yPercent: 32,
    changedArea: '2.15 ha',
    firstObservation: 'May 2026',
    sensor: 'Sentinel-2',
    processingStatus: 'COMPLETED',
    verificationStatus: 'PENDING',
  },
  {
    id: 'site-03',
    code: 'SITE-03',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    changeType: 'Industrial Expansion',
    confidence: 84,
    priority: 'MEDIUM',
    date: 'Jul 2026',
    lat: 17.6868,
    lng: 83.2185,
    xPercent: 78,
    yPercent: 22,
    changedArea: '3.40 ha',
    firstObservation: 'April 2026',
    sensor: 'Landsat-9',
    processingStatus: 'COMPLETED',
    verificationStatus: 'CONFIRMED',
    verificationTimestamp: '01 Aug 2026 • 14:15 IST',
  },
  {
    id: 'site-04',
    code: 'SITE-04',
    name: 'Guntur',
    state: 'Andhra Pradesh',
    changeType: 'Road Expansion',
    confidence: 79,
    priority: 'LOW',
    date: 'Aug 2026',
    lat: 16.3067,
    lng: 80.4365,
    xPercent: 55,
    yPercent: 62,
    changedArea: '0.95 ha',
    firstObservation: 'June 2026',
    sensor: 'Sentinel-2',
    processingStatus: 'COMPLETED',
    verificationStatus: 'REJECTED',
    verificationTimestamp: '05 Aug 2026 • 09:40 IST',
  },
];

export const SEARCH_SUGGESTIONS = [
  'Newly developed roads',
  'Construction expansion',
  'Industrial activity',
  'Vegetation change',
];

export const PROCESSING_STAGES = [
  'Understanding query',
  'Semantic retrieval',
  'Spatial filtering',
  'Temporal filtering',
  'Ranking candidate locations',
];

export const TEMPORAL_STEPS: TemporalStep[] = [
  {
    month: 'JUNE',
    year: '2026',
    status: 'Stable',
    confidence: 12,
    description: 'Baseline agricultural & natural terrain. Zero artificial linear ground scarring detected.',
  },
  {
    month: 'JULY',
    year: '2026',
    status: 'Emerging',
    confidence: 64,
    description: 'Earthwork clearing and initial linear corridor excavating visible across 1.12 ha.',
  },
  {
    month: 'AUGUST',
    year: '2026',
    status: 'Confirmed',
    confidence: 92,
    description: 'Asphalt paving completed with structural shoulder alignment across 1.84 ha total area.',
  },
];

export const FALSE_ALARM_CHECKS = [
  { name: 'Cloud interference', status: 'PASSED', detail: 'Cloud cover < 1.2%' },
  { name: 'Seasonal variation', status: 'PASSED', detail: 'Cross-validated multi-year spectral baseline' },
  { name: 'Image noise', status: 'PASSED', detail: 'Sensor radiometric calibration confirmed' },
  { name: 'Temporary surface change', status: 'PASSED', detail: 'Persistent structural change across 60+ days' },
];

export const SIMILAR_SITES: SimilarSite[] = [
  {
    id: 'sim-01',
    name: 'Anantapur',
    similarity: 94,
    changePattern: 'Road Development',
    coordinates: '15.8201° N, 77.6006° E',
    area: '1.92 ha',
  },
  {
    id: 'sim-02',
    name: 'Kadapa',
    similarity: 89,
    changePattern: 'Construction Pattern',
    coordinates: '14.4673° N, 78.8242° E',
    area: '2.10 ha',
  },
  {
    id: 'sim-03',
    name: 'Nellore',
    similarity: 84,
    changePattern: 'Infrastructure Change',
    coordinates: '14.4426° N, 79.9865° E',
    area: '1.45 ha',
  },
];

export const INITIAL_REVIEW_QUEUE: ReviewItem[] = [
  {
    id: 'NG-104',
    siteId: 'site-01',
    code: 'SITE-01',
    location: 'Kurnool Road Development',
    changeType: 'Road Development',
    confidence: 92,
    priority: 'HIGH',
    status: 'Pending',
    date: '08 Sep 2026',
  },
  {
    id: 'NG-103',
    siteId: 'site-02',
    code: 'SITE-02',
    location: 'Vijayawada Construction',
    changeType: 'Construction Expansion',
    confidence: 87,
    priority: 'MEDIUM',
    status: 'Pending',
    date: '07 Sep 2026',
  },
  {
    id: 'NG-102',
    siteId: 'site-03',
    code: 'SITE-03',
    location: 'Visakhapatnam Industrial Expansion',
    changeType: 'Industrial Expansion',
    confidence: 84,
    priority: 'MEDIUM',
    status: 'Verified',
    date: '01 Sep 2026',
  },
  {
    id: 'NG-101',
    siteId: 'site-04',
    code: 'SITE-04',
    location: 'Guntur Road Expansion',
    changeType: 'Road Expansion',
    confidence: 79,
    priority: 'LOW',
    status: 'Rejected',
    date: '28 Aug 2026',
  },
];
